## Numpy: Package for multidimensional array

In [6]:
import numpy as np

In [7]:
sample_list = [6,7,8]
np.array(sample_list)

array([6, 7, 8])

In [22]:
arr = np.array([3,4,5])
arr

array([3, 4, 5])

In [ ]:
list_of_lists = [[1,3,2],[3,4,5],[6,5,7]]
np.array(list_of_lists)

In [23]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
np.arange(1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [29]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
np.linspace(0,60,5)

array([ 0., 15., 30., 45., 60.])

In [34]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.random.rand(7,4)

array([[0.22128281, 0.85283717, 0.30316601, 0.69392714],
       [0.40736172, 0.53890563, 0.9171882 , 0.05455897],
       [0.26672224, 0.19413364, 0.75512855, 0.48656368],
       [0.46519195, 0.68710165, 0.92493084, 0.27072598],
       [0.18662511, 0.82620888, 0.01405634, 0.33935066],
       [0.7321195 , 0.86252095, 0.94130819, 0.46218244],
       [0.91930862, 0.31773276, 0.80047921, 0.70867149]])

In [36]:
arr= np.random.randn(4,5)
arr

array([[ 0.32725117,  0.096428  , -2.19200643, -1.39985386, -0.02179395],
       [-1.34645722,  0.7711311 ,  0.63885708,  0.53994015,  0.50536519],
       [-1.2343278 , -0.52586042, -1.1758375 , -0.56789559, -1.50169545],
       [ 0.12668361, -0.49421735, -0.91221936, -0.00569909,  1.4737346 ]])

In [37]:
np.random.randint(3,10)

6

In [38]:
np.random.randint(20,58,100)

array([52, 37, 24, 40, 37, 52, 42, 36, 34, 50, 35, 22, 55, 31, 27, 31, 45,
       28, 23, 31, 34, 55, 36, 22, 45, 56, 49, 34, 43, 33, 40, 52, 45, 25,
       52, 46, 26, 34, 37, 40, 33, 32, 27, 38, 36, 43, 47, 55, 37, 29, 24,
       52, 40, 33, 29, 44, 32, 48, 37, 29, 31, 30, 36, 41, 52, 33, 27, 29,
       55, 48, 55, 25, 49, 42, 52, 52, 32, 49, 22, 56, 41, 23, 28, 54, 40,
       45, 36, 51, 49, 56, 21, 39, 55, 46, 52, 21, 27, 56, 31, 34])

In [93]:
sample_array = np.random.randint(0,100,20)
sample_array

array([ 1, 58,  7, 33, 15, 82,  4, 43, 58, 83, 37, 29, 32, 25, 64, 55, 66,
       42, 53, 68])

In [19]:
import numpy as np

In [20]:
rand_array =np.random.randint(0,100,20)
rand_array

array([66, 46, 82, 49,  2, 67, 32, 94, 88,  2, 91, 81, 82, 86, 25, 71, 93,
       52, 43, 19])

In [100]:
sample_array.reshape(4,5)
sample_array

array([ 1, 58,  7, 33, 15, 82,  4, 43, 58, 83, 37, 29, 32, 25, 64, 55, 66,
       42, 53, 68])

In [95]:
rand_array.argmax()

16

In [26]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
a = np.random.rand(2,3)
a

array([[0.31970043, 0.71270288, 0.40446508],
       [0.43990152, 0.26451529, 0.71723326]])

In [28]:
rand_array=np.random.randint(0,100,20)
rand_array

array([65, 95, 97, 60, 23, 25, 43, 32, 35, 12, 88, 37, 18, 39, 54, 23, 98,
       60, 13, 65])

In [103]:
sample_array.reshape(4,5)

array([[ 1, 58,  7, 33, 15],
       [82,  4, 43, 58, 83],
       [37, 29, 32, 25, 64],
       [55, 66, 42, 53, 68]])

In [30]:
rand_array.max()

98

In [31]:
rand_array.argmax()

16

In [32]:
a=np.eye(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [33]:
a.T

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [34]:
a=np.random.rand(3,5)
a

array([[0.57052046, 0.51937971, 0.82511888, 0.36127211, 0.0422652 ],
       [0.79952859, 0.51881179, 0.72295555, 0.48883614, 0.11796386],
       [0.60200211, 0.68875362, 0.89290931, 0.38780497, 0.72369721]])

In [35]:
a.T

array([[0.57052046, 0.79952859, 0.60200211],
       [0.51937971, 0.51881179, 0.68875362],
       [0.82511888, 0.72295555, 0.89290931],
       [0.36127211, 0.48883614, 0.38780497],
       [0.0422652 , 0.11796386, 0.72369721]])

In [36]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
sample_array[6]

16

In [39]:
sample_array[5:6]

array([15])

In [40]:
sample_array[2:5]=100
sample_array

array([ 10,  11, 100, 100, 100,  15,  16,  17,  18,  19,  20])

In [41]:
sample_array=np.arange(10,31)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [42]:
sample_array[0:9]

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [43]:
subset_sample_array[:]=1001
subset_sample_array

NameError: name 'subset_sample_array' is not defined

## TWO DIMENSIONAL ARRAY

In [44]:
import numpy as np

In [45]:
sample_matrix=np.array(([1,2,3],[4,5,6],[7,8,9]))
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
sample_matrix[1,2]

6

In [60]:
sample_matrix[2:1]

array([], shape=(0, 3), dtype=int32)

In [48]:
sample_matrix[2]

array([7, 8, 9])

In [55]:
sample_matrix[2]

array([7, 8, 9])

In [61]:
sample_matrix[1:2]

array([[4, 5, 6]])

In [71]:
sample_matrix[:,[2,]]

array([[3],
       [6],
       [9]])

## Selection techniques

In [ ]:
smaple_array=np.arange(1,20)

In [21]:
sample_array

array([64,  3,  0, 76, 24, 97, 77, 11, 93, 84, 11, 67, 58, 64, 18,  5, 90,
       25, 58, 64])

In [72]:
sample_array+sample_array

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60])

In [73]:
np.exp(sample_array)

array([2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
       1.20260428e+06, 3.26901737e+06, 8.88611052e+06, 2.41549528e+07,
       6.56599691e+07, 1.78482301e+08, 4.85165195e+08, 1.31881573e+09,
       3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
       1.95729609e+11, 5.32048241e+11, 1.44625706e+12, 3.93133430e+12,
       1.06864746e+13])

In [74]:
np.sqrt(sample_array)

array([3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558])

In [77]:
np.log(sample_array)

array([2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
       3.40119738])

In [78]:
np.max(sample_array)

30

In [79]:
np.min(sample_array)

10

In [80]:
np.argmax(sample_array)

20

In [81]:
np.argmin(sample_array)

0

In [82]:
np.square(sample_array)

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484,
       529, 576, 625, 676, 729, 784, 841, 900])

In [83]:
np.std(sample_array)

6.0553007081949835

In [84]:
np.var(sample_array)

36.666666666666664

In [85]:
np.mean(sample_array)

20.0

In [86]:
array=np.random.randn(3,4)
array

array([[ 0.52568027,  0.01584172,  2.29849554,  1.70689426],
       [ 0.48514914,  0.16198756,  0.59268828,  0.02465789],
       [-0.91198347,  2.31203246,  0.52338841,  0.15860943]])

In [91]:
sports=np.array(['golf','race','jump','ball'])
np.unique(sports)

array(['ball', 'golf', 'jump', 'race'], dtype='<U4')